name: Simple Workflow

on:
  workflow_dispatch:

jobs:
  say-hi:
    runs-on: ubuntu-latest
    steps:
      - name: Print hi
        run: echo "hi"

      - name: Print Done
        run: echo "Done"
